### ISSUE TITLE
RABBITMQ_LOGS=- is not supported on Windows

### ISSUE THREAD

**Issue by AceHack** [rabbitmq/rabbitmq-server#1348]
Commit 53af45bf9a162dec849407d114041aad3d84feaf introduced stdout logging but not for Windows.

**Comment by hairyhum** [comment]
Logging in Windows should work the same way, but apparently we had a typo in the `.bat` file, which made it think that `-` should be treated as a file name. Fixed in the linked PR.

**Comment by hairyhum** [comment]
Please note that for windows service console logs are still disabled, because service console is not available.

**Comment by AceHack** [comment]
Still not working on 3.6.12 even after this fix.

  ##########  Logs: C:/rabbitmq/sbin/-
  ######  ##        C:/rabbitmq/sbin/-

**Comment by michaelklishin** [comment]
@AceHack `3.6.12` [does not include this fix](https://github.com/rabbitmq/rabbitmq-server/releases/tag/rabbitmq_v3_6_12). See this issue's milestone: it's set to `3.6.13`.

**Comment by michaelklishin** [comment]
If anyone would like to test this change, use a [recent 3.6.13 snapshot build](https://dl.bintray.com/rabbitmq/all-dev/rabbitmq-server/) which are [available from Bintray](http://www.rabbitmq.com/snapshots.html).

**Comment by AceHack** [comment]
Okay tested with 3.6.13 and it's working great!! Thanks.
