### ISSUE TITLE
Management API returned status code 431 after login with oidc connect

### ISSUE THREAD

**Issue by colbacc8** [rabbitmq/rabbitmq-server#13761]
### Is your feature request related to a problem? Please describe.

I have a RabbitMQ 3.13.7 instance that is connected to an OIDC Keycloak service.

The issue I'm encountering occurs when users with very large tokens try to access the RabbitMQ dashboard.
The error shown on the dashboard is: "Management API returned status code 431", which should be related to headers that are too large.

I've cleaned the browser cache, removed the cookies, tried different browser. Nothing worked. 

As a test, I created a new user in Keycloak, and that user was able to access the dashboard without any issues.

I tried several configuration options in RabbitMQ to increase the header size, but none of them worked.
For example, I set initial_frame_size to a fairly large value, but the problem persisted.

### Describe the solution you'd like

I'd like to have the possibility to enlarge the header size to allow users with large token

**Comment by colbacc8** [comment]
issue solved with the advanced configuration by adding the following:

```yaml
[
    { rabbitmq_management, [
            { listener, [
                    { cowboy_opts, [{ max_header_value_length, 262144 } ]}
            ]}
        ]
    }
].
```

**Comment by michaelklishin** [comment]
Perhaps that setting is worth increasing (by default) and exposing to `rabbitmq.conf`, I'm discussing this with the team.

**Comment by huweikkk** [comment]
> Perhaps that setting is worth increasing (by default) and exposing to `rabbitmq.conf`, I'm discussing this with the team.

I encountered the same issue in version 4.2, but adjusting the configuration didn't resolve it. Is there a solution?
