### ISSUE TITLE
RabbitMQ slack channel problem

### ISSUE THREAD

**Issue by abunch** [rabbitmq/rabbitmq-server#1760]
<img width="1262" alt="screenshot 2018-11-05 11 09 10" src="https://user-images.githubusercontent.com/2077840/48014070-7cc4aa80-e0eb-11e8-9a41-6c49c666a076.png">

**Comment by lukebakken** [comment]
Thanks for reporting this. We're aware of this issue and are trying to reach the app's owner. This is not something maintained by the core RabbitMQ team.

FWIW, the [mailing list](https://groups.google.com/forum/#!forum/rabbitmq-users) should be used in the future for something like this. Have a good day.

**Comment by lukebakken** [comment]
@abunch this is now resolved.

**Comment by aashikam** [comment]
I still get this error. 
<img width="1680" alt="screen shot 2019-02-14 at 4 26 11 pm" src="https://user-images.githubusercontent.com/39673615/52782589-742e2980-3075-11e9-8fc6-1ef6e1e62d6e.png">

**Comment by aashikam** [comment]
I still get this error. 

<img width="1680" alt="screen shot 2019-02-14 at 4 30 10 pm" src="https://user-images.githubusercontent.com/39673615/52782741-d25b0c80-3075-11e9-80bc-e159992f4377.png">

**Comment by michaelklishin** [comment]
We will restage the app. Please post your observations about the self-service app to the mailing list and not GitHub issues.
