### ISSUE TITLE
rabbit_reader doesn't handle exit signals from the socket process, when it's terminating channels

### ISSUE THREAD

**Issue by Ayanda-D** [rabbitmq/rabbitmq-server#544]
When [`rabbit_reader`](https://github.com/rabbitmq/rabbitmq-common/blob/master/src/rabbit_reader.erl) terminates channels using [`rabbit_reader:wait_for_channel_termination/3`](https://github.com/rabbitmq/rabbitmq-common/blob/master/src/rabbit_reader.erl#L744), it sets an [aggregate timeout](https://github.com/rabbitmq/rabbitmq-common/blob/master/src/rabbit_reader.erl#L733), proportional to all channels, upon which it will issue a [`cancel_wait`](https://github.com/rabbitmq/rabbitmq-common/blob/master/src/rabbit_reader.erl#L734) message, which results in a [`channel_termination_timeout`](https://github.com/rabbitmq/rabbitmq-common/blob/master/src/rabbit_reader.erl#L767) exception. During [`wait_for_channel_termination`](https://github.com/rabbitmq/rabbitmq-common/blob/master/src/rabbit_reader.erl#L744), the socket process may terminate and issue an exit signal to [`rabbit_reader`](https://github.com/rabbitmq/rabbitmq-common/blob/master/src/rabbit_reader.erl). (Which is likely, as [`rabbit_writer`](https://github.com/rabbitmq/rabbitmq-common/blob/master/src/rabbit_writer) would also be carrying out some port operations to [flush](https://github.com/rabbitmq/rabbitmq-common/blob/master/src/rabbit_channel.erl#L478) out any data still held in the TCP buffers, aynchronously). Exit signals from the port are currently not handled, and could lead to [`channel_termination_timeout`](https://github.com/rabbitmq/rabbitmq-common/blob/master/src/rabbit_reader.erl#L767) exceptions. Side effects of this could vary, i.e. on operations carried out during the period when the socket has terminated, but channel Pids are still alive, or rather, are in the process of being terminated, up until the timing out of [`wait_for_channel_termination`](https://github.com/rabbitmq/rabbitmq-common/blob/master/src/rabbit_reader.erl#L744). The exception below illustrates a scenario where an unhandled `{'EXIT',#Port<0.22137>,normal}` message from the socket was received by [`rabbit_reader`](https://github.com/rabbitmq/rabbitmq-common/blob/master/src/rabbit_reader.erl), and should have resulted in its immediate and normal termination (along with normal clean up procedures), instead of a continued wait for channels to terminate, and eventual termination by [`channel_termination_timeout exception`](https://github.com/rabbitmq/rabbitmq-common/blob/master/src/rabbit_reader.erl#L767).

```
=CRASH REPORT==== 14-Dec-2015::16:49:05 ===
  crasher:
    initial call: rabbit_reader:init/4
    pid: <0.7418.0>
    registered_name: []
    exception exit: channel_termination_timeout
      in function  rabbit_reader:wait_for_channel_termination/3 (src/rabbit_reader.erl, line 766)
      in call from rabbit_reader:send_error_on_channel0_and_close/4 (src/rabbit_reader.erl, line 1503)
      in call from rabbit_reader:terminate/2 (src/rabbit_reader.erl, line 615)
      in call from rabbit_reader:handle_other/2 (src/rabbit_reader.erl, line 540)
      in call from rabbit_reader:mainloop/4 (src/rabbit_reader.erl, line 502)
      in call from rabbit_reader:run/1 (src/rabbit_reader.erl, line 427)
      in call from rabbit_reader:start_connection/4 (src/rabbit_reader.erl, line 385)
    ancestors: [<0.7416.0>,<0.2520.0>,<0.2519.0>,<0.2518.0>,rabbit_sup,
                  <0.634.0>]
    messages: [{'EXIT',#Port<0.22137>,normal}]
    links: []
    dictionary: [{{channel,1},
                   {<0.7445.0>,{method,rabbit_framing_amqp_0_9_1}}},
                  {process_name,
                      {rabbit_reader,
                          <<"192.168.245.8:48658 -> 192.168.245.3:5672">>}},
                  {{ch_pid,<0.7445.0>},{1,#Ref<0.0.0.40007>}}]
    trap_exit: true
    status: running
    heap_size: 2586
    stack_size: 27
    reductions: 7946
  neighbours:
```

**Comment by Ayanda-D** [comment]
Could be related to #530.

**Comment by michaelklishin** [comment]
Should be fixed by https://github.com/rabbitmq/rabbitmq-common/pull/47.

**Comment by lemenkov** [comment]
Just for the record, after all these patches applied I still see it regularly. This one is made by RabbitMQ 3.6.3

=CRASH REPORT==== 20-Jun-2017::23:41:57 ===
  crasher:
    initial call: rabbit_reader:init/4
    pid: <0.18631.0>
    registered_name: []
    exception exit: channel_termination_timeout
      in function  rabbit_reader:wait_for_channel_termination/3 (src/rabbit_reader.erl, line 767)
      in call from rabbit_reader:send_error_on_channel0_and_close/4 (src/rabbit_reader.erl, line 1504)
      in call from rabbit_reader:terminate/2 (src/rabbit_reader.erl, line 612)
      in call from rabbit_reader:handle_other/2 (src/rabbit_reader.erl, line 537)
      in call from rabbit_reader:mainloop/4 (src/rabbit_reader.erl, line 499)
      in call from rabbit_reader:run/1 (src/rabbit_reader.erl, line 424)
      in call from rabbit_reader:start_connection/4 (src/rabbit_reader.erl, line 382)
    ancestors: [<0.18628.0>,<0.336.0>,<0.335.0>,<0.334.0>,rabbit_sup,
                  <0.77.0>]
    messages: [{'EXIT',#Port<0.13578>,normal}]
    links: []
    dictionary: [{{channel,1},
                   {<0.18644.0>,{method,rabbit_framing_amqp_0_9_1}}},
                  {{ch_pid,<0.18644.0>},{1,#Ref<0.0.10.3477>}},
                  {process_name,
                      {rabbit_reader,
                          <<"11.120.0.10:38434 -> 11.120.0.10:5672">>}}]
    trap_exit: true
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 1593123
  neighbours:

**Comment by michaelklishin** [comment]
@lemenkov FWIW we haven't seen this stack trace in a while (3.6.3 is a year old).

**Comment by lemenkov** [comment]
@michaelklishin lucky you! I'm investigating this currently - I'll ping you if I find anything.

**Comment by lemenkov** [comment]
@michaelklishin back to this issue. Actually we've got these messages with 3.6.5 as well. So what I've got here is that.

I've got 3 nodes A,B,C.

Node C is experiencing some connectivity issues (lost heartbeats from clients).

      =ERROR REPORT==== 22-Jan-2018::11:00:21 ===
      closing AMQP connection <0.2203.2> (10.210.8.9:60368 -> 10.210.8.7:5672 - nova-compute:43126:5a13b6b0-31c6-453b-bacc-51f5066c9888):
      missed heartbeats from client, timeout: 60s

Node C is going down.

      =INFO REPORT==== 22-Jan-2018::11:02:38 ===
      Stopping RabbitMQ

      =INFO REPORT==== 22-Jan-2018::11:02:38 ===
      stopped TCP Listener on 10.210.8.7:5672

      =INFO REPORT==== 22-Jan-2018::11:02:38 ===
      Stopped RabbitMQ application

      =INFO REPORT==== 22-Jan-2018::11:02:38 ===
      Halting Erlang VM

Node A noticed C going offline:

      =INFO REPORT==== 22-Jan-2018::11:02:38 ===
      Mirrored queue 'reply_aa2bb108ffb344288ea16efce66e4164' in vhost '/': Slave <rabbit@jncloud-controller-0.2.16099.0> saw deaths of mirrors <rabbit@jncloud-controller-2.1.6441.0>

      =INFO REPORT==== 22-Jan-2018::11:02:39 ===
      node 'rabbit@jncloud-controller-2' down: connection_closed

      =INFO REPORT==== 22-Jan-2018::11:02:44 ===
      Stopping RabbitMQ

      =INFO REPORT==== 22-Jan-2018::11:02:44 ===
      stopped TCP Listener on 10.210.8.1:5672

And here I've got a strange crash report:

...............
```
      =CRASH REPORT==== 22-Jan-2018::11:02:47 ===
        crasher:
          initial call: rabbit_reader:init/4
          pid: <0.17029.1>
          registered_name: []
          exception exit: channel_termination_timeout
            in function  rabbit_reader:wait_for_channel_termination/3 (src/rabbit_reader.erl, line 771)
            in call from rabbit_reader:send_error_on_channel0_and_close/4 (src/rabbit_reader.erl, line 1508)
            in call from rabbit_reader:terminate/2 (src/rabbit_reader.erl, line 616)
            in call from rabbit_reader:handle_other/2 (src/rabbit_reader.erl, line 541)
            in call from rabbit_reader:mainloop/4 (src/rabbit_reader.erl, line 503)
            in call from rabbit_reader:run/1 (src/rabbit_reader.erl, line 428)
            in call from rabbit_reader:start_connection/4 (src/rabbit_reader.erl, line 386)
          ancestors: [<0.17027.1>,<0.17093.0>,<0.17091.0>,<0.17089.0>,rabbit_sup,
                        <0.747.0>]
          messages: [{'EXIT',#Port<0.16148>,normal}]
          links: []
          dictionary: [{{channel,1},
                         {<0.17037.1>,{method,rabbit_framing_amqp_0_9_1}}},
                        {{ch_pid,<0.17037.1>},{1,#Ref<0.0.1.157017>}},
                        {credit_flow_default_credit,{200,50}},
                        {process_name,
                            {rabbit_reader,
                                <<"10.210.8.1:58502 -> 10.210.8.1:5672 - nova-conductor:916198:cfb9f0d8-33bd-4cc4-97a4-75e6d1652eb0">>}},
                        {{credit_from,<0.17037.1>},199}]
          trap_exit: true
          status: running
          heap_size: 1598
          stack_size: 27
          reductions: 5548
        neighbours:
```
...............

Later Node A stopped.

      =INFO REPORT==== 22-Jan-2018::11:02:49 ===
      Stopped RabbitMQ application

      =INFO REPORT==== 22-Jan-2018::11:02:49 ===
      Halting Erlang VM

What happened is the following sequence of the events in src/rabbit_reader.erl:

1. I receive {'EXIT',#Port<0.16148>,normal} from the closed socket
```
mainloop(Deb, Buf, BufLen, State = #v1{sock = Sock,
                                       connection_state = CS,
                                       connection = #connection{
                                         name = ConnName}}) ->
    Recv = rabbit_net:recv(Sock),
    ...
    case Recv of
        ...
        % Other == {'EXIT',#Port<0.16148>,normal} here
>>>     {other, Other}  ->
            case handle_other(Other, State) of
                stop     -> ok;
                NewState -> recvloop(Deb, Buf, BufLen, NewState)
            end
    end.
```   
 2. Instead of acting fast and cleaning up immediately, rabbit_reader follows the standard ```handle_other(...)``` procedure where it sends some messages back to the closed socket.
 3. Eventually it waits in ```wait_for_channel_termination(...)``` for ```{'EXIT', Sock, _Reason}``` after which it must cleanup socket as the following:
 ```
       [channel_cleanup(ChPid, State) || ChPid <- all_channels()],
            exit(normal);
 ```
 4. Already dead socket never send anything back, so it has timeout instead and exits with ```exit(channel_termination_timeout)```.
 
 The question is that - should we just add ```{other, {'EXIT', Sock, _Reason}}``` match expression before ```{other, Other}``` and initiate channel_cleanup right there, w/o passing it down through handle_other? From a first glance I don't see a lot of trouble here.

**Comment by michaelklishin** [comment]
Yes, it makes sense to handle normal exits from the socket and terminate early. Thanks for digging in this.

I feel we should modify some error messages to produce a different message when the process is waiting for something other than channels and hitting a timeout.

Either way this is just log noise but log noise sometimes translates into severity 1 escalations, so we are all for reducing it.

**Comment by michaelklishin** [comment]
Clean stops in `mainloop/4` make sense, the only thing I'd test is whether all dependents such as channels are cleaned up correctly but they should be or we have a different (and bigger) problem.

**Comment by michaelklishin** [comment]
unfortunately our team couldn't find a way to reproduce the scenario described in https://github.com/rabbitmq/rabbitmq-server/issues/544#issuecomment-371504926 but we're testing a PR that incorporates @lemenkov's idea in #1550, which will ship in 3.6.16 and 3.7.5.

I'm not going to change the milestone because the issue as originally reported was addressed in 3.6.1,
and https://github.com/rabbitmq/rabbitmq-server/issues/544#issuecomment-371504926 describes is a different scenario which produces an identical stack trace in the logs (but is still nothing more than log noise).
