### ISSUE TITLE
Dead-lettering a message second time crashes the queue

### ISSUE THREAD

**Issue by dhaval-gusani** [rabbitmq/rabbitmq-server#767]
Hi,

The use case is we dead-letter message after several retries, if it is because of some external dependency of consumer, we replay those dead-letter messages to the actual queue again. But consider that the external dependency again goes down, and the consumer tries to dead-letter those messages again, the queue crashes.

I am attaching java client used to simulating the scenario.

Steps to follow to simulate scenario
1. create a dead-letter queue
2. Run the java client to publish and consume message.

I am also attaching the error from rabbitmq logs

[rabbitmq-files.zip](https://github.com/rabbitmq/rabbitmq-server/files/231086/rabbitmq-files.zip)

**Comment by michaelklishin** [comment]
I'm pretty sure this is https://github.com/rabbitmq/rabbitmq-server/issues/216 which is already fixed.

**Comment by michaelklishin** [comment]
By the way, if you think it's a separate issue that looks very similar, please let us know.

**Comment by dhaval-gusani** [comment]
Actually I tried this on 3.5.6 and 3.6.1, and still occurred.

**Comment by hairyhum** [comment]
@dhaval-gusani 
There are 
`headers.put("x-death", "[{queue=some-queue, time=Thu Mar 17 22:44:51 UTC 2016, count=1, reason=rejected, routing-keys=[some-queue], exchange=}]");` line that sets `x-death` header to string of some format. `x-death` should be array of tables and it doesn't look like java client can transform this string to array.
Can you tell where did you get this string?

**Comment by michaelklishin** [comment]
This happens when a message was dead-lettered or federated, and then consumed and re-published by an app. The best we can do is to filter out string values and start from scratch.

**Comment by michaelklishin** [comment]
So this is very similar to https://github.com/rabbitmq/rabbitmq-federation/issues/12.

**Comment by michaelklishin** [comment]
Client libraries cannot be responsible for filtering out such headers. In practice most of them won't. RabbitMQ should be more defensive and ignore the headers it uses when they are provided by clients but pass validation (however we define "validation").
