### ISSUE TITLE
Since 3.11.11, not all dependencies are included into the source distribution

### ISSUE THREAD

**Issue by VlkrS** [rabbitmq/rabbitmq-server#7869]
### Describe the bug

Starting with 3.11.11 ```make install``` invoked in a full distribution requires a network connection to pull in at least ```mix_task_archive_deps```.

Before 3.11.10, the distribution was largely self-contained. Is that an intentional change or an unintentional consequence of a different change?

### Reproduction steps

1. Download rabbitmq-server-3.11.11.tar.xz or later
2. invoke ```make install``` without an active network connection
3. Build fails trying to install ```mix_task_archive_deps```

### Expected behavior

Build succeeds without network access, as on 3.11.10 and earlier.

### Additional context

Attempted to update the port on OpenBSD (which disables network access for port builds) succeeded with versions up till 3.11.10, failed with 3.11.11, 3.11.12 and 3.11.13. There's ways to work around this for the port, but I wanted to check in if that's an intentional change first.

**Comment by michaelklishin** [comment]
It is a build time dependency. I doubt the change was intentional but the need to support offline builds is something that different team members have different views on.

Mix usually fetches all of its dependencies from remote sources. As part of #7845 we are reconsidering the role of `mix_task_archive_deps`.

**Comment by VlkrS** [comment]
Thanks for the feedback! I don't have strong feelings one way or another, but the pre-3.11.11 releases were definitely easier to package.

**Comment by michaelklishin** [comment]
I suspect it should be fairly easy to go back to how things were before `3.11.11` but let's wait for someone who has the context to come back to work.

**Comment by michaelklishin** [comment]
This should be addressed by #7875. @VlkrS I'll post a link to a source tarball once the pipeline succeeds.

**Comment by michaelklishin** [comment]
See [development releases](https://github.com/rabbitmq/rabbitmq-server-binaries-dev/releases), with the most recent 3.12 and 3.11 builds. They should include source tarballs.

**Comment by VlkrS** [comment]
I'm still failing to install rabbitmq from rabbitmq-server-3.11.16.tar.xz. Running ```make install-erlapp·install-scripts·install-bin·install-man``` always hits missing dependencies when calling ```mix deps.get```, even when I patch out the installation of ```mix_task_archive_deps```.

**Comment by michaelklishin** [comment]
@pjk25 @dumbbell so offline make-based builds still fail :(

**Comment by VlkrS** [comment]
@pjk25: With #8204 applied, the offline build works for me on OpenBSD and at a (very) quick glance the resulting package works.

**Comment by pjk25** [comment]
Thanks for testing it @VlkrS
